# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pDayInRangeCppVec <- function(min, max, lwr_temp, upr_temp) {
    .Call(`_rcpppDay_pDayInRangeCppVec`, min, max, lwr_temp, upr_temp)
}

rcpp_hello_world <- function() {
    .Call(`_rcpppDay_rcpp_hello_world`)
}

